version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src/"
    schedule:
      interval: "monthly"
  
    open-pull-requests-limit: 5

    commit-message:
      prefix: "[pip-updates]"

    groups:
      pip-updates:
        patterns:
          - "*"
          
    assignees:
      - "pawong"
